bot:
  token: ${BOT_TOKEN}
  goldenDickChance: 0.05
  bombChance: 0.05

spring:
  datasource:
    url: jdbc:h2:file:./test.db
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:1}
management:
  influx:
    metrics:
      export:
        enabled: false
---
spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
